name: Node Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node: [18]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Set git name/email
        run: |
          git config --global user.email "bids.maintenance@gmail.com"
          git config --global user.name "bids-maintenance"
      - name: Set up Node
        run: |
          npm install -g npm@^7
          npm install
      - name: Eslint
        run: npm run lint
      - name: Get bids-examples data
        run: git submodule update --init
      - name: Jest tests
        run: npm run coverage -- --maxWorkers=2 --testTimeout=10000 --colors
      - name: Upload to codecov
        run: npm run codecov
      - name: Smoke tests
        run: |
          bids-validator/bin/bids-validator bids-validator/tests/data/valid_headers/ --ignoreNiftiHeaders
          bids-validator/bin/bids-validator bids-validator/tests/data/valid_headers/ --ignoreNiftiHeaders --json
