name: test-bids-examples

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        bids-examples-branch: [master]

    runs-on: ${{ matrix.platform }}

    env:
      TZ: Europe/Berlin
      FORCE_COLOR: 1

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Upgrade npm
        run: npm install --global npm

      - name: Install bids-validator
        run: |
          npm install
          npm link ./bids-validator
          echo "./node_modules/.bin" >> $GITHUB_PATH

      - name: Get bids-examples data
        run: |
          git clone --depth 1 https://github.com/bids-standard/bids-examples

      - name: Display versions and environment information
        run: |
          echo $TZ
          export PATH="../node_modules/.bin:$PATH"
          date
          echo "npm"; npm --version
          echo "node"; node --version
          echo "bids-validator"; bids-validator --version
          which bids-validator
          ls -a $(which bids-validator)

      - name: Validate all BIDS datasets using bids-validator
        run: |
          export PATH="../node_modules/.bin:$PATH"
          cat ./run_tests.sh
          bash ./run_tests.sh
        shell: bash
        working-directory: ./bids-examples
